### ISSUE TITLE
Script dies after some time

### ISSUE THREAD

**Issue by lucasgautheron** [Paul255/actionfps_ts3bot#1]
Script works fine until it just die.

Had to use 

```
while true;
do
    python ts3bot.py;
    sleep 1;
done
```

Any idea ?

**Comment by Paul255** [comment]
Might be a timeout from the connection to the serve, i made the bot connect, message and disconnect.
We'll see if it's better

**Comment by lucasgautheron** [comment]
Looks like it's now fixed.
